name: Deploy storybook on GitHub pages

on:
  push:
    branches: master

env:
  NODE_VERSION: 14.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build storybook
        run: npm run build-storybook
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
